---
title: "MetMiner cookbook"
subtitle: "Large-scale Plant Metabolomics Data Processing and Data Mining"
page-layout: full
---

### Project

**MetMiner:** A user-friendly pipeline for large-scale plant metabolomics data analysis.

This is the documentation of **MetMiner**. You can get up-to-date verison from the GitHub repository <https://github.com/ShawnWx2019/MetMiner>.

In this pipeline, [tidyMass](https://www.tidymass.org/) @shen_tidymass_2022 take on the majority of the upstream data analysis, data cleaning, and metabolite annotation tasks.

Furthermore, we have developed a Metabolomics Downstream Analysis toolkit [MDAtoolkits](https://github.com/ShawnWx2019/MDAtoolkits/tree/master) and a user-friendly [WGCNA Shiny app](https://github.com/ShawnWx2019/WGCNA-shinyApp). They are responsible for the downstream analysis and data mining section.

The metMiner shiny app has been packaged into a [TBtools](https://github.com/CJ-Chen/TBtools-II) @chen_tbtools-ii_2023 plugin, which can be downloaded and installed through the TBtools plugin store. Thanks to TBtools for providing a convenient dependency resolution solution. 

### Citation

If you have utilized MetMiner in your project, please cite:

1.  Xiao Wang, Shuang Liang, Ke Yu, Wenqi Yang, Bing Zhao, Fei Liang, Xiang Zhu, Chao Zhou, Luis A. J. Mur, Jeremy A, Roberts, Junli Zhang,and Xuebin Zhang. 2024 "MetMiner: A user-friendly pipeline for large-scale plant metabolomics data analysis"

2.  Shen, Xiaotao, Hong Yan, Chuchu Wang, Peng Gao, Caroline H. Johnson, and Michael P. Snyder. 2022. "TidyMass an Object-Oriented Reproducible Analysis Framework for LC Data." Nature Communications 13 (1): 4365. https://doi.org/10.1038/s41467-022-32155-w.
